In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\Unemployment_Rate_upto_11_2020.csv")

In [3]:
df.head()

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Region.1,longitude,latitude
0,Andhra Pradesh,31-01-2020,M,5.48,16635535,41.02,South,15.9129,79.74
1,Andhra Pradesh,29-02-2020,M,5.83,16545652,40.90,South,15.9129,79.74
2,Andhra Pradesh,31-03-2020,M,5.79,15881197,39.18,South,15.9129,79.74
3,Andhra Pradesh,30-04-2020,M,20.51,11336911,33.10,South,15.9129,79.74
4,Andhra Pradesh,31-05-2020,M,17.43,12988845,36.46,South,15.9129,79.74

In [4]:
df.tail()

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Region.1,longitude,latitude
262,West Bengal,30-06-2020,M,7.29,30726310,40.39,East,22.9868,87.855
263,West Bengal,31-07-2020,M,6.83,35372506,46.17,East,22.9868,87.855
264,West Bengal,31-08-2020,M,14.87,33298644,47.48,East,22.9868,87.855
265,West Bengal,30-09-2020,M,9.35,35707239,47.73,East,22.9868,87.855
266,West Bengal,31-10-2020,M,9.98,33962549,45.63,East,22.9868,87.855

In [5]:
df.columns

Index(['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Region.1', 'longitude', 'latitude'],
      dtype='object')

In [6]:
df.columns = ['state','date','frequency','estimated unemployment rate','estimated employed','estimated labour participation rate','region','longitude','latitude']

In [7]:
df.head()

,state,date,frequency,estimated unemployment rate,estimated employed,estimated labour participation rate,region,longitude,latitude
0,Andhra Pradesh,31-01-2020,M,5.48,16635535,41.02,South,15.9129,79.74
1,Andhra Pradesh,29-02-2020,M,5.83,16545652,40.90,South,15.9129,79.74
2,Andhra Pradesh,31-03-2020,M,5.79,15881197,39.18,South,15.9129,79.74
3,Andhra Pradesh,30-04-2020,M,20.51,11336911,33.10,South,15.9129,79.74
4,Andhra Pradesh,31-05-2020,M,17.43,12988845,36.46,South,15.9129,79.74

In [8]:
df.isnull().sum()

state                                  0
date                                   0
frequency                              0
estimated unemployment rate            0
estimated employed                     0
estimated labour participation rate    0
region                                 0
longitude                              0
latitude                               0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   state                                267 non-null    object
 1   date                                 267 non-null    object
 2   frequency                            267 non-null    object
 3   estimated unemployment rate          267 non-null    float64
 4   estimated employed                   267 non-null    int64
 5   estimated labour participation rate  267 non-null    float64
 6   region                               267 non-null    object
 7   longitude                            267 non-null    float64
 8   latitude                             267 non-null    float64
dtypes: float64(4), int64(1), object(4)
memory usage: 18.9+ KB

In [10]:
df.shape

(267, 9)

In [13]:
df.describe()

,estimated unemployment rate,estimated employed,estimated labour participation rate,longitude,latitude
count,267.000000,2.670000e+02,267.000000,267.000000,267.000000
mean,12.236929,1.396211e+07,41.681573,22.826048,80.532425
std,10.803283,1.336632e+07,7.845419,6.270731,5.831738
min,0.500000,1.175420e+05,16.770000,10.850500,71.192400
25%,4.845000,2.838930e+06,37.265000,18.112400,76.085600
50%,9.650000,9.732417e+06,40.390000,23.610200,79.019300
75%,16.755000,2.187869e+07,44.055000,27.278400,85.279900
max,75.850000,5.943376e+07,69.690000,33.778200,92.937600

In [14]:
df.duplicated().any()

np.False_

In [15]:
df.state.value_counts()

state
Andhra Pradesh      10
Assam               10
Bihar               10
Chhattisgarh        10
Delhi               10
Goa                 10
Gujarat             10
Haryana             10
Himachal Pradesh    10
Jharkhand           10
Karnataka           10
Rajasthan           10
Kerala              10
Madhya Pradesh      10
Maharashtra         10
Meghalaya           10
Odisha              10
Puducherry          10
Punjab              10
Uttarakhand         10
Tamil Nadu          10
Telangana           10
Tripura             10
West Bengal         10
Uttar Pradesh       10
Jammu & Kashmir      9
Sikkim               8
Name: count, dtype: int64

In [16]:
df['date'] = pd.to_datetime(df['date'],dayfirst=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   state                                267 non-null    object
 1   date                                 267 non-null    datetime64[ns]
 2   frequency                            267 non-null    object
 3   estimated unemployment rate          267 non-null    float64
 4   estimated employed                   267 non-null    int64
 5   estimated labour participation rate  267 non-null    float64
 6   region                               267 non-null    object
 7   longitude                            267 non-null    float64
 8   latitude                             267 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 18.9+ KB

In [17]:
df['month_int'] = df['date'].dt.month
df.head()

,state,date,frequency,estimated unemployment rate,estimated employed,estimated labour participation rate,region,longitude,latitude,month_int
0,Andhra Pradesh,2020-01-31,M,5.48,16635535,41.02,South,15.9129,79.74,1
1,Andhra Pradesh,2020-02-29,M,5.83,16545652,40.90,South,15.9129,79.74,2
2,Andhra Pradesh,2020-03-31,M,5.79,15881197,39.18,South,15.9129,79.74,3
3,Andhra Pradesh,2020-04-30,M,20.51,11336911,33.10,South,15.9129,79.74,4
4,Andhra Pradesh,2020-05-31,M,17.43,12988845,36.46,South,15.9129,79.74,5

In [18]:
import calendar
df['month'] = df['month_int'].apply(lambda x: calendar.month_abbr[x])
df.head()

,state,date,frequency,estimated unemployment rate,estimated employed,estimated labour participation rate,region,longitude,latitude,month_int,month
0,Andhra Pradesh,2020-01-31,M,5.48,16635535,41.02,South,15.9129,79.74,1,Jan
1,Andhra Pradesh,2020-02-29,M,5.83,16545652,40.90,South,15.9129,79.74,2,Feb
2,Andhra Pradesh,2020-03-31,M,5.79,15881197,39.18,South,15.9129,79.74,3,Mar
3,Andhra Pradesh,2020-04-30,M,20.51,11336911,33.10,South,15.9129,79.74,4,Apr
4,Andhra Pradesh,2020-05-31,M,17.43,12988845,36.46,South,15.9129,79.74,5,May

In [19]:
data = df.groupby(['month'])[['estimated unemployment rate','estimated employed',
                              'estimated labour participation rate']].mean()
data = pd.DataFrame(data).reset_index()
data

,month,estimated unemployment rate,estimated employed,estimated labour participation rate
0,Apr,22.236154,1.057020e+07,35.297308
1,Aug,10.313333,1.442904e+07,42.390741
2,Feb,9.266154,1.548827e+07,44.180769
3,Jan,9.196538,1.563720e+07,44.626538
4,Jul,9.834444,1.441802e+07,42.274815
5,Jun,10.911111,1.385739e+07,41.203333
6,Mar,10.782593,1.453866e+07,43.746667
7,May,23.244444,1.150739e+07,39.647778
8,Oct,8.026296,1.457998e+07,41.438519
9,Sep,8.705926,1.458784e+07,41.974444

In [20]:
import plotly.graph_objects as go

month = data.month
unemployment_rate = data['estimated unemployment rate']
labour_participation_rate = data['estimated labour participation rate']

fig = go.Figure()

fig.add_trace(go.Bar(x = month,y = unemployment_rate,name='estimated unemployment rate' ))
fig.add_trace(go.Bar(x = month, y = labour_participation_rate,name='estimated labour participation rate'))

fig.update_layout(title= 'Unemployment Rate and Labour Participation',
                  xaxis = {'categoryorder':'array','categoryarray':['jan','Feb',
               'Mar','Apr','May','Jun','July','Aug','sep','Oct']} )

fig.show()

In [21]:
import plotly.express as px

In [31]:
fig = px.bar(data,x='month',y = 'estimated employed',color='month',
             category_orders={'month':['jan','feb','mar','apr','May','Jun','Jul','Aug','Sept','Oct']},
             title='Estimated employed people from jan 2020 to oct 2020'
             )
fig.show()

In [32]:
state =  df.groupby(['state'])[['estimated unemployment rate','estimated employed',
                                'estimated labour participation rate']].mean()
state = pd.DataFrame(state).reset_index()

In [33]:
fig = px.bar(state,x = 'state',y='estimated unemployment rate',color='state',
             title='Average Unemployment rate (State)')
fig.update_layout(xaxis={'categoryorder':'total descending'})
plt.show()